Feature/cron
Pomidor-Studio/SportCRM pull request #100
Opened 2019-03-23 17:12 UTC by keldkemp

Планировщик под команды

2019-03-23 17:21 UTC, ciklop submitted a review, later dismissed

2019-03-23 18:24 UTC, INovozhilov requested changes

2019-03-23 18:24 UTC, INovozhilov commented on bot/views.py
> +        return HttpResponse(status=404)
404 - это страница не найдена. Нужно возвращать либо 400 либо 422

2019-03-23 18:24 UTC, INovozhilov commented on bot/views.py
> +    for module in modules:
Странная конструкция.
Определись, либо у тебя каждая процедура в своём файле, тогда нужно назвать сами процедуры одинаково, либо собрать их в одном файле. Перебирать одновременно и файлы и искать в них процедуры - ну странно.

В цикле, если нашел метод, из цикла надо выходить. 
Вместо обработки UnboundLocalError лучше проверить ` if method_to_call`

2019-03-23 19:44 UTC, keldkemp commented on bot/views.py
> +    for module in modules:
Давай цикл оставим, задел на будущее, вдруг захотим какие то определенные события в отдельный файл вынести

2019-03-24 05:30 UTC, INovozhilov approved these changes

2019-03-25 12:53 UTC, ciklop approved these changes

2019-03-25 12:53 UTC, merged