Beatify client edit balance form
Pomidor-Studio/SportCRM pull request #101
Opened 2019-03-23 19:18 UTC by ciklop

2019-03-23 20:08 UTC, INovozhilov requested changes

2019-03-23 20:08 UTC, INovozhilov commented on crm/models.py
>              ClientBalanceChangeHistory.objects.get_or_create(
кажется, что get_or_create - это ошибка и должно быть просто create

2019-03-23 20:08 UTC, INovozhilov commented on crm/templates/crm/manager/balance/form.html
> +  <link
а нельзя, чтобы джанго сама подключала нужные css и js виджетов через form.media?

2019-03-23 20:26 UTC, ciklop commented on crm/templates/crm/manager/balance/form.html
> +  <link
теоретически - можно. но фактически это вливается в то что надо анализировать контекст, находить там формы, и как-то понимать - надо ли выводить медиа или нет. 
по этому универсального решения нет, и делается это руками.

2019-03-24 04:52 UTC, INovozhilov approved these changes

2019-03-24 04:52 UTC, merged