Кнопки "сохранить и добавить еще" на абонементах, клиентах, тренерах …
Pomidor-Studio/SportCRM pull request #108
Opened 2019-03-28 00:36 UTC by RomanBoyars

…и локациях

2019-03-28 06:25 UTC, ciklop requested changes

2019-03-28 06:25 UTC, ciklop commented on crm/views/manager/client.py
> +    def post(self, request, *args, **kwargs):
Сделай на это дело Mixin, который будет переопределять post и брать параметр редиректа из `self.another_form_redirect` и тогда дублирования кода не будет

2019-03-29 18:59 UTC, ciklop approved these changes

2019-03-29 19:14 UTC, INovozhilov approved these changes

2019-03-29 19:14 UTC, merged