Excel import
Pomidor-Studio/SportCRM pull request #109
Opened 2019-03-28 03:49 UTC by RomanBoyars

2019-03-28 06:44 UTC, ciklop requested changes

2019-03-28 06:44 UTC, ciklop commented on crm/templatetags/html_helper.py
> +def vk_user_id(vk_ref):
в html_helper этому делать нечего, в шаблонах этот код не используется, по этому его надо вынести в либо в utils либо в vk_utils. 
Ну и да, по хорошему - код vk_small_avatar тоже надо вынести туда, а в def vk_small_avatar оставить только вызов той функциии. Но вот это, уже в рамках отдельного PR

2019-03-28 06:44 UTC, ciklop commented on crm/views/manager/client.py
> +                m = re.search("vk.com\/(?P<id>([A-Za-z0-9_])+)", row[cell.column_index_from_string(vk_col) - 1].value)
уже есть `utils.VK_PAGE_REGEXP` к которому надо применять search

2019-03-28 06:44 UTC, ciklop commented on crm/views/manager/client.py
> +                vk = vk_user_id(vk_ref)
А вот определение vk id клиента надо сделать butch операцией, так как клиентов может быть тысяча - то столько за раз нам ВК просто не даст сделать запросов.

Т.е. в начале создаем клиентов, и сохраняем список ID клиента, VK строка из файла. Потом одним запросом получаем список всех пользователей, и идём по ответу и дописываем vk id. ВК возвращает список пользователей в том порядке в котором было передано, по этому сопоставление уже будет кто есть кто.

2019-03-28 06:44 UTC, ciklop commented on crm/views/manager/client.py
> +                client = Client.objects.create(
Это очень тонкий момент - ведь если я второй раз загружу один и тот-же файл, у меня задублируются данные. Нужна проверка на существования такой записи ученика. Ну и такая проверка позволит избежать использования транзакции - если функция посредине работы упала, то повторная загрузка файла "досоздаст" недостающих

2019-04-03 15:21 UTC, ciklop submitted a review, later dismissed

2019-04-03 15:25 UTC, ciklop approved these changes

2019-04-03 17:03 UTC, INovozhilov approved these changes

2019-04-03 17:03 UTC, merged