Page subscriptions new
Pomidor-Studio/SportCRM pull request #113
Opened 2019-03-28 08:29 UTC by Vlasov1994

2019-03-28 11:24 UTC, ciklop commented on crm/views/manager/subscription.py
> +    # form_class = SubscriptionsTypeForm
А зачем убран кусок?

2019-03-28 11:24 UTC, ciklop commented on crm/views/manager/subscription.py
> +from django.shortcuts import get_object_or_404
Импорт без использования?

2019-03-28 15:41 UTC, INovozhilov requested changes

2019-03-28 15:41 UTC, INovozhilov commented on crm/templates/crm/manager/subscription/form.html
> +          <button class="btn btn-primary btn-outline-info" type="submit">{% if object.id %}Сохранить{% else %}Добавить{% endif %}</button>
btn-primary и btn-outline-info - противоречат друг другу. Добавляя один - нужно убирать второй

2019-03-30 15:46 UTC, ciklop submitted a review, later dismissed

2019-03-31 06:57 UTC, INovozhilov submitted a review, later dismissed

2019-03-31 07:01 UTC, INovozhilov approved these changes

2019-03-31 07:01 UTC, INovozhilov approved these changes

2019-03-31 07:01 UTC, merged