Name colission
Pomidor-Studio/SportCRM pull request #120
Opened 2019-03-28 20:54 UTC by ciklop

Имя пользователя должно быть уникальным среди всех пользователей, игнорируя компанию - иначе будут проблемы с сопоставлением паролей. По этому сделал проверку уникальности игнорируя текущий tenant

2019-03-29 19:05 UTC, INovozhilov requested changes

2019-03-29 19:05 UTC, INovozhilov commented on contrib/forms.py
> +            set_current_tenant(current_tenant)
разве set_current_tenant не надо делать независимо от IF, т.е. в любом случае?

2019-03-29 19:05 UTC, INovozhilov commented on contrib/forms.py
> +class NonTenantUsernameMixin:
Может лучше в TenantModelForm добавить скрытый менеджер, который не фильтруется по company? Или это небезопасно?

2019-03-30 08:50 UTC, ciklop commented on contrib/forms.py
> +class NonTenantUsernameMixin:
Там же проблема в том что для нормальной работы get_user_model зависимых функций - что-то должно быть уникальным по всей базе. у нас это username (вариант по умолчанию), и хоть user привязан к company - username всё равно должен быть уникальным.

И такой "скрытый" менеджер нужен по факту только в одном месте - при работе с username, а если его делать - то придётся добавлять логику - когда его включать, а когда нет. Что собственно мы и делаем включая в класс этот конкретный миксин. Сама операция set_current_tenant - очень "дешевая", там просто на thread local перемнную садится значение. По этому можно в нескольких конкретных местах просто "временно забыть" про tenant

2019-03-30 10:24 UTC, INovozhilov approved these changes

2019-03-30 10:24 UTC, merged