One time visits fix
Pomidor-Studio/SportCRM pull request #136
Opened 2019-04-03 01:03 UTC by RomanBoyars

2019-04-03 07:41 UTC, ciklop requested changes

2019-04-03 07:41 UTC, ciklop commented on crm/forms.py
> +        'data-onetime': str(subs.one_time),
Лучше привести к int и проверку делать на 1 чем на `True`

2019-04-05 15:32 UTC, ciklop submitted a review, later dismissed

2019-04-05 17:27 UTC, INovozhilov submitted a review, later dismissed

2019-04-05 18:18 UTC, INovozhilov approved these changes

2019-04-05 18:18 UTC, merged