Запрет на изменение даты активности компании INTERNAL
Pomidor-Studio/SportCRM pull request #151
Opened 2019-04-05 14:05 UTC by RomanBoyars

2019-04-05 15:34 UTC, ciklop requested changes

2019-04-05 15:34 UTC, ciklop commented on crm/models.py
> +        if self.display_name == 'INTERNAL' and self.active_to != None:
Проверять надо по `self.name` и по `crm.models.INTERNAL_COMPANY`, а не display_name и строковому литералу

2019-04-09 17:48 UTC, ciklop approved these changes

2019-04-10 18:51 UTC, INovozhilov approved these changes

2019-04-10 18:51 UTC, merged