Excel import 2
Pomidor-Studio/SportCRM pull request #153
Opened 2019-04-07 17:16 UTC by RomanBoyars

2019-04-07 18:16 UTC, ciklop requested changes

2019-04-07 18:16 UTC, ciklop commented on crm/views/manager/client.py
> +        self.request.session['import_errors'] = errors
если ты это делаешь в одном view - то тебе сессия не нужна. запиши errors в self, и переопредели get_context_data в котором будешь проверять - есть ли в self errors, и если есть - добавлять в контекст.

2019-04-07 18:16 UTC, ciklop commented on crm/templatetags/html_helper.py
> +def get_duplicate_indeces(seq,item):
это всё лучше переписать на такой вариант
```python
return [index for index, value in enumerate(seq) if value == item]
```

2019-04-07 18:16 UTC, ciklop commented on crm/templates/crm/manager/client/import_report.html
> +          {% for k, v in request.session.import_errors.items %}
надо переделать на вариант с контекстом

2019-04-08 01:59 UTC, RomanBoyars commented on crm/views/manager/client.py
> +        self.request.session['import_errors'] = errors
так это разные view

2019-04-08 02:04 UTC, RomanBoyars commented on crm/templatetags/html_helper.py
> +def get_duplicate_indeces(seq,item):
такой вариант будет дольше выполняться
https://stackoverflow.com/questions/5419204/index-of-duplicates-items-in-a-python-list/23294343

2019-04-08 10:51 UTC, ciklop commented on crm/templatetags/html_helper.py
> +def get_duplicate_indeces(seq,item):
Да, тут согласен, этот вариант быстрее.

2019-04-08 10:53 UTC, ciklop commented on crm/views/manager/client.py
> +        self.request.session['import_errors'] = errors
Тогда надо чистить данные из сесии после чтения либо не давать просто так заходить на страницу. 
Суть в том что на эту страницу можно попасть прямым образом, и в сесии будут висеть устаревшие данные. Такое лучше подчищать

2019-04-08 15:17 UTC, ciklop submitted a review, later dismissed

2019-04-08 19:07 UTC, INovozhilov requested changes

2019-04-08 19:07 UTC, INovozhilov commented on crm/templatetags/html_helper.py
>          if screen_name in vk_user_domains:
что это за извращение? Цикл внутри цикла. Напиши обычный один цикл по vk_user_domains с одним IF внутри.
Будет работать быстро, и будет легко читаться.

2019-04-08 19:07 UTC, INovozhilov commented on crm/views/manager/client.py
> +                phone_raw = row[cell.column_index_from_string(phone_col) - 1].value
а phone_col может быть не задан? Например если пользователь не хочет импортировать телефон (нет его).

2019-04-08 19:07 UTC, INovozhilov commented on crm/views/manager/client.py
> +                name = row[cell.column_index_from_string(name_col) - 1].value
column_index_from_string -1 - сохранил бы уже в переменные и не дергал каждый раз в цикле.

2019-04-08 19:07 UTC, INovozhilov commented on crm/views/manager/client.py
> +                phone = re.sub("\D", "", str(phone_raw))
Лучше бы в отдельную функцию вынести, для облегчения читаемости и упрощения дальнейшей доработки импорта.

2019-04-08 19:07 UTC, INovozhilov commented on crm/views/manager/client.py
> +                balance = float(row[cell.column_index_from_string(balance_col) - 1].value.replace(',','.'))
в отдельную функцию

2019-04-08 19:07 UTC, INovozhilov commented on crm/views/manager/client.py
> +                errors["{}{}".format(birthday_col, index+1)] = "Неверный формат даты. Допустимые форматы: ГГГГ-ММ-ДД, ДД.ММ.ГГГГ, ДД/ММ/ГГГГ, ДД-ММ-ГГГГ."
Текст с перечислением допустимх форматов должен жить недалеко от самих форматов. Иначе при изменении будет сложно синхронизировать

2019-04-08 19:07 UTC, INovozhilov commented on crm/views/manager/client.py
>          for vk_user_id in vk_user_ids:
Цикл в цикле где он вроде как не нужен.

2019-04-09 15:44 UTC, RomanBoyars commented on crm/views/manager/client.py
> +                phone_raw = row[cell.column_index_from_string(phone_col) - 1].value
Ну это не предусмотрено, это тогда лучше сделать галочку на всех опциональных столбцах. В задаче не было сказано ничего про опциональные столбцы.

2019-04-09 15:44 UTC, RomanBoyars commented on crm/views/manager/client.py
> +                phone_raw = row[cell.column_index_from_string(phone_col) - 1].value
Там форма не позволит отправить с пустым полем

2019-04-09 16:51 UTC, RomanBoyars commented on crm/views/manager/client.py
> +                phone = re.sub("\D", "", str(phone_raw))
что я должен вынести в отдельные функции? Блоки try-except, там они завязаны на цикл, их не получится вынести.

2019-04-09 16:52 UTC, RomanBoyars commented on crm/views/manager/client.py
> +                errors["{}{}".format(birthday_col, index+1)] = "Неверный формат даты. Допустимые форматы: ГГГГ-ММ-ДД, ДД.ММ.ГГГГ, ДД/ММ/ГГГГ, ДД-ММ-ГГГГ."
текст с перечислением форматов недалеко от самих форматов это как? у меня функция парсинга даты в html_helper, я тогда туда напишу ALLOWED_DATE_FORMATS константу?

2019-04-10 20:03 UTC, ciklop submitted a review, later dismissed

2019-04-11 15:42 UTC, INovozhilov submitted a review, later dismissed

2019-04-11 16:07 UTC, INovozhilov approved these changes

2019-04-11 16:07 UTC, merged