Sell and mark fixes
Pomidor-Studio/SportCRM pull request #160
Opened 2019-04-09 18:38 UTC by RomanBoyars

2019-04-09 19:12 UTC, ciklop requested changes

2019-04-09 19:12 UTC, ciklop commented on crm/templates/crm/manager/event/detail.html
> +        $select_elem = $('#{{ sell_subscription_form.subscription.id_for_label }}').select2('data');
Надо добавить `let` перед переменной. И переименовать её в camelCase `$selectedElem`. Бесячий момент, но в python принять snake_case, в js camelCase - и этого правила надо придерживаться. Линтеры на такое сразу ругаются.

2019-04-09 19:12 UTC, ciklop commented on crm/templates/crm/manager/event/detail.html
> +        fillFields($select_elem[0])
`;` нет

2019-04-09 19:12 UTC, ciklop commented on crm/templates/crm/manager/event/detail.html
> +          fillFields(e.params.data)
`;`

2019-04-09 19:12 UTC, ciklop commented on crm/templates/crm/manager/event/sell-and-mark.html
> +      $select_elem = $('#{{ form.subscription.id_for_label }}').select2('data');
Тоже что и выше

2019-04-10 18:24 UTC, ciklop approved these changes

2019-04-10 18:47 UTC, INovozhilov approved these changes

2019-04-10 18:51 UTC, merged