Берем клиентов исходя из записи на тренировку.
Pomidor-Studio/SportCRM pull request #192
Opened 2019-04-15 19:36 UTC by khunafin

2019-04-16 15:59 UTC, INovozhilov requested changes

2019-04-16 15:59 UTC, INovozhilov commented on bot/tasks.py
> +        id__in=event.attendance_set.filter(marked=False, signed_up=True)
Так ведь ты получишь только тех, кто записался на тренировку. Нужны же те, у кого есть абонемент на занятие независимо от того, записались ли они или нет. вроде with_active_subscription_to_event.

2019-04-19 05:07 UTC, ciklop approved these changes

2019-04-19 07:10 UTC, INovozhilov approved these changes

2019-04-19 07:10 UTC, merged