Report for events (not working)
Pomidor-Studio/SportCRM pull request #22
Opened 2019-02-24 18:05 UTC by RomanBoyars

2019-02-28 06:20 UTC, ciklop requested changes

2019-02-28 06:20 UTC, ciklop commented on crm/filters.py
> +        initial_data['date_after'] = datetime.today().replace(day=1)
как мне кажется, синтаксис pendulum выглядит более понятным
```python
start_of_month = pendulum.today().start_of('month')
initial_data['date_after'] = start_of_month
initial_data['date_before'] = start_of_month.add(months=1)
```

2019-02-28 06:20 UTC, ciklop commented on crm/filters.py
> +from django_select2.forms import Select2MultipleWidget, ModelSelect2MultipleWidget, Select2Widget, Select2TagWidget, \
Надо добавить в requirements.txt

2019-02-28 06:20 UTC, ciklop commented on crm/filters.py
> +        super().__init__(initial_data , queryset, request=request, prefix=prefix)
Проверял на других месяцах, кроме текущего?
Такая передача initial_data перетрет значение от клиента. И в отчете всегда будет текущий месяц.
Надо добавить проверку на наличие полей в запросе. И если их нет, то тогда только менять.

2019-02-28 06:20 UTC, ciklop commented on crm/filters.py
> +        super().__init__(initial_data , queryset, request=request, prefix=prefix)
И назвать лучше не initial_data, а with_defaults_data, так как это не initial ни разу

2019-02-28 06:20 UTC, ciklop commented on crm/filters.py
> +        #self.form['date'].initial = ['27.02.2019', '27.02.2019']
Лишние ошметки кода и множественные пустые линии.

2019-02-28 06:20 UTC, ciklop commented on crm/models.py
> +            (self.date_to and self.date_to < day):
Не надо трогать это форматирование, это по pep8

2019-02-28 06:20 UTC, ciklop commented on crm/models.py
> +        self, start_date: date, end_date: date) -> Dict[date, 'Event']:
Не надо трогать это форматирование, это по pep8

2019-02-28 06:20 UTC, ciklop commented on crm/models.py
> +        queryset = ClientSubscriptions.objects.filter(subscription__in=
Кошмарное форматирование. 
```python
queryset = ClientSubscriptions.objects.filter(
    subscription__in=SubscriptionsType.objects.filter(
        event_class=self.event_class, visit_limit=1
    ),
    purchase_date=self.date,
    start_date=self.date,
    client__in=[
        attendance.client 
        for attendance in self.attendance_set.all()
    ]
)
```

2019-02-28 06:20 UTC, ciklop commented on crm/models.py
> +        if queryset:
queryset всегда будет
```python
return queryset.count()
```

2019-02-28 06:20 UTC, ciklop commented on crm/models.py
> +        return 0
До этого return вообще никогда не добраться

2019-02-28 06:20 UTC, ciklop commented on crm/models.py
> +        queryset = ClientSubscriptions.objects.filter(subscription__in=
Можно сделать ещё проще, и эффективнее
```python
queryset = <твой qs>.values_list('price', flat=True)

return sum(list(queryset))  # Возможно и без cast to list сработает
```

2019-02-28 06:20 UTC, ciklop commented on crm/templates/crm/manager/event/report.html
> +{{ filter.form.media.js }}
не будет работать на сервере, так как в crm.settings.base нет в INSTALLED_APPS django_select2

2019-03-02 15:54 UTC, INovozhilov requested changes

2019-03-02 15:54 UTC, INovozhilov commented on crm/models.py
> +    def get_clients_count(self):
Название функции нужно более наглядное. Что речь именно о посетивших тренировку клиентах

2019-03-02 15:54 UTC, INovozhilov commented on crm/models.py
> +    def get_clients_count_one_time_sub(self):
В таком виде только как временное решение. У одноразовых абонементов наверное будет более явный признак, чем количество посещений. 
Поставь TODO:

2019-03-02 17:04 UTC, ciklop submitted a review, later dismissed

2019-03-02 17:33 UTC, INovozhilov approved these changes

2019-03-02 17:34 UTC, merged