Тренировка (#17)
Pomidor-Studio/SportCRM pull request #225
Opened 2019-05-06 09:02 UTC by ionoff

### Замечания по изменениям
- Элементы списка учеников были порезано, а то разметку трудно смотреть + DRY
- Добавлены Актуальные CSS, JS, IMG из Trello

### Вопросы
- "Подробнее о занятии" -- пока не сверстано
- "Удалить все занятия" и "Отменить текущее занятие" -- требуется разъяснение
- Если нет абонемента, то кнопка "оплатить" означает "продать", верно ли это?

2019-05-06 16:13 UTC, khunafin commented on crm/templates/crm/manager/event/detail.html
>  {% block content %}
Нужен блок для меню в мобильной версии со стрелкой назад

2019-05-06 16:17 UTC, khunafin requested changes
Нужно проверить в мобильной версии как выглядит

2019-05-07 18:41 UTC, khunafin approved these changes

2019-05-08 05:10 UTC, ionoff commented
Предлагаю влить на дев, так будет более понятно что к чему, если что фиксанем по мелочи.

2019-05-08 05:45 UTC, merged