Замечания по продлению абонементов
Pomidor-Studio/SportCRM pull request #24
Opened 2019-02-25 20:16 UTC by RomanBoyars

2019-02-25 20:51 UTC, ciklop requested changes

2019-02-25 20:51 UTC, ciklop commented on crm/models.py
> +    def is_extended(self):
```python
@property
def is_extended(self):
    return self.extensionhistory_set.exists()
```

2019-02-25 20:51 UTC, ciklop commented on crm/models.py
> +        while True:
end_date = date(2019, 1, 30)
events = [EventClass(date_to=date(2019, 1, 29))]

Цикл не закончится никогда.

2019-02-25 20:51 UTC, ciklop commented on crm/forms.py
> +        self.fields['visit_limit'].initial = 1
Зачем этот тут? Можно же перенести в visit_limit = ...(label=..., initial=1)
А `__init__` убрать.

2019-02-26 07:28 UTC, ciklop commented on crm/models.py
> +        while True:
https://github.com/Pomidor-Studio/SportCRM/pull/25/files#diff-909cbe310ab612e31f8b055c8c57ed34R230

Вот в этой ветке правильная функция возвращающая следующую дату занятия

2019-03-02 16:09 UTC, INovozhilov approved these changes

2019-03-02 16:09 UTC, ciklop approved these changes

2019-03-02 16:09 UTC, merged