Добавил вывод кнопок на каждый действующий абонемент клиента, добавил…
Pomidor-Studio/SportCRM pull request #28
Opened 2019-02-28 14:07 UTC by Vlasov1994

Добавил вывод кнопок на каждый действующий абонемент клиента
Добавил методы списывания посещений и их возврата

2019-02-28 15:57 UTC, ciklop submitted a review, later dismissed

2019-02-28 16:19 UTC, INovozhilov requested changes

2019-02-28 16:19 UTC, INovozhilov commented on crm/models.py
> +    def mark_the_visit(self, visit_count=1):
Метод какой-то не правильный. 
Он должен ещё отметку о посещении сохранять, а не только уменьшать количество посещений.

2019-02-28 16:19 UTC, INovozhilov commented on crm/models.py
> +    def reimburse_visit(self, visit_count=1):
слово reimburse - не то

2019-02-28 16:19 UTC, INovozhilov commented on crm/views/manager/event_class.py
> +            'subscriptions': client_subscriptions
решение с dictionary решил не делать?

2019-02-28 16:57 UTC, Vlasov1994 commented on crm/views/manager/event_class.py
> +            'subscriptions': client_subscriptions
Забыл про это, записи об этом моменте оставил дома, а доделывал на работе. Сейчас займусь

2019-03-01 09:39 UTC, Vlasov1994 commented on crm/views/manager/event_class.py
> +            'subscriptions': client_subscriptions
@INovozhilov я правильно помню что ты предлагал сделать ключом Dict сделать нейм клиента, а значением массив из абонементов клиента? Если да то это не очень хороший вариант в том плане что куча действий лишних появляется. Не думаю что это целесообразно делать. Если же я не правильно помню что ты предлагал, напомни, пожалуйста.

2019-03-01 17:36 UTC, ciklop submitted a review, later dismissed

2019-03-01 18:28 UTC, INovozhilov commented on crm/views/manager/event_class.py
> +            'subscriptions': client_subscriptions
Сделай отдельный словарь с ид клиента, чтобы меньше циклов в темплейте было.

2019-03-02 14:09 UTC, INovozhilov requested changes

2019-03-02 14:09 UTC, INovozhilov commented on crm/views/manager/event_class.py
> +                    clients.append(client)
Сложно написано. зачем коллекция, проверяй наличие client среди ключей clients_subscriptions

2019-03-02 14:09 UTC, INovozhilov commented on crm/views/manager/event_class.py
> +                    client_subscriptions = clients_subscriptions.get(client)
Зачем присваивание? Почему не clients_subscriptions[client].append()

2019-03-02 15:16 UTC, INovozhilov approved these changes

2019-03-02 15:19 UTC, merged