Scanner
Pomidor-Studio/SportCRM pull request #35
Opened 2019-03-03 12:03 UTC by INovozhilov

2019-03-03 14:12 UTC, ciklop requested changes

2019-03-03 14:12 UTC, ciklop commented on crm/models.py
> +    qr_code = models.SlugField("QR код", blank=True, null=True, unique=True)
Лучше сделать UUIDField на базе uuid4, там добьётся относительно гарантированная уникальность кода и защита от подбора брутфорсом.

2019-03-03 14:12 UTC, ciklop commented on crm/models.py
> +class ClientAttendanceExist(Exception):
...Exist**s**

2019-03-03 14:12 UTC, ciklop commented on crm/models.py
> +                new_obj, created = Attendance.objects.get_or_create(event=event,
```python
new_obj, created = Attendance.objects.get_or_create(
    event=event, client=self.client, defaults={'subscription': self}
)
```

или 

```python
new_obj, created = Attendance.objects.get_or_create(
    event=event, 
    client=self.client, 
    defaults={'subscription': self}
)
```

Читаемее

2019-03-03 14:12 UTC, ciklop commented on crm/templates/crm/manager/event/scanner.html
> +      console.log(content);
В прод коде не должно быть console.log

2019-03-03 14:12 UTC, ciklop commented on crm/templates/crm/manager/event/scanner.html
> +      let scanner = new Instascan.Scanner({ video: document.getElementById('preview'),  mirror: false, backgroundScan: false });
Теоретически let доступен почти везде в актуальном, https://caniuse.com/#feat=let, но лучше для ручного кода использовать "классику es5" - var

2019-03-03 14:12 UTC, ciklop commented on crm/views/manager/event_class.py
> +    LoginRequiredMixin,
LoginRequiredMixin не надо использовать, а надо PermissionRequiredMixin

```
permission_required = 'some-perm'
```

и есть такой rule
```python
rules.add_perm(
    'event.mark_attendance',
    is_logged_manager | is_editable_by_coach
)
```

2019-03-03 14:12 UTC, ciklop commented on crm/views/manager/event_class.py
> +    # def __init__(self, *args, **kwargs):
Лишнего кода тоже не должно быть в проде.
Если коммент не несущий смысла - лучше сразу убирать, чтоб не засорять код

2019-03-03 14:12 UTC, ciklop commented on crm/views/manager/event_class.py
> +class Scanner(
Эту view лучше распилить на две шутуки. Потому что это S в SOLID -> Single-responsiblity principle, класс должен делать только одну вещь
Одна которая просто template выводит.
А вторая - наследуется от crm.view.mixin.RedirectWithActionView

```python
pattern_name = 'crm:manager:event-class:event:scanner'

def run_action(self):
    # do action here
```

2019-03-03 14:12 UTC, ciklop commented on crm/views/manager/event_class.py
> +                self.extra_context['warning'] = f'Ученик с QR кодом {code} не найден'
Такие фокусы не нужны. Есть django.contrib.messages

Пример - https://github.com/Pomidor-Studio/SportCRM/blob/master/crm/views/manager/coach.py#L139

И соответственно в шаблоне ну нужно это выводить. Вывод таких сообщений сделан в базовом шаблоне

2019-03-03 14:12 UTC, ciklop commented on crm/views/manager/event_class.py
> +        self.extra_context = {'event': event}
После распила на две view такое не нужно будет делать, так как RedirectActionView и так вернёт обратно тот-же урл, со всеми параметрами

2019-03-03 14:12 UTC, ciklop commented on crm/urls.py
> +        name='scanner'
не могут быть два одинаковых name. reverse не сможет вычислить правильный url

2019-03-03 14:16 UTC, ciklop requested changes

2019-03-03 14:16 UTC, ciklop commented on sportcrm/urls.py
> +    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),
url это старый вариант
```python
path('qr_code/', include(('qr_code.urls', 'qr_code'), namespace="qr_code")),
```

2019-03-03 14:16 UTC, ciklop commented on sportcrm/urls.py
> +    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),
Тогда и импортировать ничего не надо

2019-03-03 15:32 UTC, INovozhilov commented on crm/models.py
> +    qr_code = models.SlugField("QR код", blank=True, null=True, unique=True)
Да, скорее всего так и будет. Но сейчас пока не очень ясна модель как qr коды ассоциировать с клиентами. 
Но подумаю ещё.

2019-03-03 15:52 UTC, INovozhilov commented on crm/urls.py
> +        name='scanner'
Могут, и работает) И где-то я такой подход даже видел то ли в доке то ли ещё где-то в интернетах. Но ок.

2019-03-03 15:57 UTC, INovozhilov commented on sportcrm/urls.py
> +    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),
Взял из документации к этому модулю. Чтож они пишут то так...

2019-03-03 15:59 UTC, INovozhilov commented on crm/templates/crm/manager/event/scanner.html
> +      console.log(content);
Это вообще сплошной черновик(
И сама библиотка очень тяжелая - 1.5 МБ!!! Есть 80кб билблиотеки, попробую попозже её подключить.

2019-03-03 16:53 UTC, INovozhilov commented on crm/models.py
> +    qr_code = models.SlugField("QR код", blank=True, null=True, unique=True)
Ещё я боюсь, что ссылки с настоящим uuid будут слишком длинными, и qr код будет излишне сложным. надо бы его упаковать, т.к. в виде обычной hex строки он занимает слишком много места. но как 16 байт упаковать в массив, который хорошо поддерживается qr кодированием?

Проблема в том, что штрихкоды надо бы в виде носителей делать. А они получаются достаточно с мелкими деталями

2019-03-03 17:31 UTC, ciklop commented on crm/urls.py
> +        name='scanner'
Хм, видимо изменения какие-то были, и он от количества аргументов высчитывает. Надо будет исходники глянуть.

2019-03-03 17:33 UTC, ciklop commented on crm/models.py
> +    qr_code = models.SlugField("QR код", blank=True, null=True, unique=True)
![frame](https://user-images.githubusercontent.com/193642/53698882-4e8a7980-3e04-11e9-81e8-4ea72702842e.png)

Нормальный такой QR код, и считать его проще чем bar-code

2019-03-03 17:34 UTC, ciklop commented on crm/templates/crm/manager/event/scanner.html
> +      console.log(content);
Вопрос не к либе, её вес малозначим. Вопрос именно к наличию console.log

2019-03-03 17:34 UTC, ciklop commented on sportcrm/urls.py
> +    url(r'^qr_code/', include(qr_code_urls, namespace="qr_code")),
Это джанго пре2.0 стайл. Доки видимо не обновляли просто

2019-03-04 05:26 UTC, ciklop requested changes

2019-03-04 05:26 UTC, ciklop commented on crm/views/manager/event_class.py
> +    def get(self, request, *args, **kwargs):
Этот весь get нужно заменить на 
```python
def get_contest_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['event'] = self.get_object()
    return context
```
почему? потому что блок ```if code``` не выполняется никогда для этого view

2019-03-04 05:26 UTC, ciklop commented on crm/views/manager/event_class.py
> +    def run_action(self):
Я честно говоря не понимаю любовь к многовложенным if-ам. Очень муторно читать, особенно когда последний else всего в одну строчку. Гораздо красивее логику инвертировать, и добавить ранний выход.
И тогда два плюса появляются - про чтении кода сразу понятна логика когда выходим из функции, и понятно что дальше "читать не надо". И второй момент - индентация, её меньше, и всё аккуратнее.

И да - self.kwargs.pop('code') избавляет нас от перегрузки get_success_url

```python
def run_action(self):
    code = self.kwargs.pop('code')

    if not code:
        return

    try:        
        client = Client.objects.get(qr_code=UUID(code))
    except ValueError:
        messages.error(self.request, f'Некорректный формат кода "{code}"')
        return 
    except Client.DoesNotExist:
        messages.error(self.request, f'Ученик с QR кодом {code} не найден')
        return

    
    event = self.get_object()
    subscription = (
        ClientSubscriptions.objects
        .active_subscriptions(event)
        .filter(client=client)
        .order_by('purchase_date')
        .first()
    )

    if not subscription:
        messages.warning(self.request, f'У {client} нет действующего абонемента')
        return

    try:
        subscription.mark_visit(event)
    except ClientAttendanceExists:
        messages.warning(self.request, f'{client} уже отмечен')
    else:
        messages.info(self.request, f'{client} отмечен по абонементу {subscription}')
```

2019-03-04 05:26 UTC, ciklop commented on crm/migrations/0010_auto_20190304_0037.py
> +            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='QR код'),
Технически blank=True и null=True можно было бы и убрать. У клиента всегда будет UUID, ну и сделать его нередактируемым из адмикни. Зачем эту техническую инфу редактировать? Разве что клиент захочет красивый UUID типа ffff-aaaa-eeee-bbbb. Стоимость хранения uuid копеечная, и заморачиваться с его возможным отсутствием тоже странно.

2019-03-04 17:29 UTC, INovozhilov commented on crm/migrations/0010_auto_20190304_0037.py
> +            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='QR код'),
Редактировать его надо. Сбрасывать в null  - пока не знаю, возможно так и останется.

2019-03-04 17:35 UTC, INovozhilov commented on crm/views/manager/event_class.py
> +    def run_action(self):
Куча вложенных ифов тоже мне не нравится. просто раньше был один return в конце, а потом он пропал... 
Для этого и нужен ревью)

2019-03-04 17:36 UTC, INovozhilov commented on crm/views/manager/event_class.py
> +    def run_action(self):
> И да - self.kwargs.pop('code') избавляет нас от перегрузки get_success_url
А как же solid? Вообще не очевидное действие.

2019-03-04 17:47 UTC, ciklop commented on crm/views/manager/event_class.py
> +    def run_action(self):
> Куча вложенных ифов тоже мне не нравится. просто раньше был один return в конце, а потом он пропал...

Если у def нет return, то считается что ```return None```.
Точно также как если стоит ```return```, то это эквивалентно ```return None```

2019-03-04 17:48 UTC, ciklop commented on crm/views/manager/event_class.py
> +    def run_action(self):
>>И да - self.kwargs.pop('code') избавляет нас от перегрузки get_success_url

>А как же solid? Вообще не очевидное действие.

Вот тут, да, согласен неоднозначный момент.

2019-03-04 20:27 UTC, ciklop approved these changes

2019-03-04 20:27 UTC, merged