Feature/vk_bot_settings
Pomidor-Studio/SportCRM pull request #36
Opened 2019-03-03 16:06 UTC by keldkemp

Настройки для ВК теперь хранятся в таблицу company

2019-03-03 16:11 UTC, keldkemp commented
Забыл убрать метод у тренера и менеджера "vk_message_token" пока тестил. Оставляем или убрать лучше? Просто может в дальнейшем пригодится

2019-03-03 16:26 UTC, keldkemp commented
А, проверьте еще в рамках этого PR "bot/api/client_receivables.py" - это метод по дебиторской задолженности

2019-03-03 20:03 UTC, INovozhilov requested changes

2019-03-03 20:03 UTC, INovozhilov commented on crm/models.py
> +    vk_group_id = models.CharField('ИД группы вк', max_length=20, unique=True, null=True)
null=true требует и blank=true иначе ввести пустое название не получится

2019-03-03 20:03 UTC, INovozhilov commented on crm/models.py
> +        return Company.objects.get(id=self.company_id).access_token
Выглядит очент странно. Зачем делать проперти в котором вычитывается компания заново? Почему нельзя просто использовать company.access_token?

2019-03-03 20:03 UTC, INovozhilov commented on crm/models.py
> +    access_token = models.CharField('Токен группы вк', max_length=100, unique=True, null=True)
Добавить префиксы - vk_access_token , vk_confirmation_token

2019-03-03 20:03 UTC, INovozhilov commented on crm/models.py
> +        return Company.objects.get(id=self.company_id).access_token
аналогично предыдущему комментарию

2019-03-04 04:54 UTC, ciklop commented on crm/models.py
> +        return Company.objects.get(id=self.company_id).access_token
:+1: в комментарии же было return self.company.vk_token

2019-03-04 17:25 UTC, ciklop approved these changes

2019-03-04 17:49 UTC, INovozhilov approved these changes

2019-03-04 17:49 UTC, merged