One time sub
Pomidor-Studio/SportCRM pull request #38
Opened 2019-03-03 21:16 UTC by RomanBoyars

2019-03-04 17:32 UTC, INovozhilov requested changes

2019-03-04 17:32 UTC, INovozhilov commented on crm/models.py
> +    one_time = models.BooleanField("Разовый абонемент", editable=False, default=False)
В модели не должно быть такого поля. Стоимость разовой тренировки берется из соответсвующего абонемента. Перечитай задачу ещё раз, в ней это было описано.

2019-03-04 19:50 UTC, INovozhilov requested changes

2019-03-04 19:50 UTC, INovozhilov commented on crm/views/manager/client.py
> +            client.save()
Нужно транзакцию организовать вместе с сохранением. Не уверен, что в этом методе получится это сделать.
А ещё лучше чтобы сохранение абонемента шло через функцию модели и сразу списывало или нет деньги (а в дальнейшем и фиксировало списание в истории баланса )

2019-03-04 19:50 UTC, INovozhilov commented on crm/views/manager/event_class.py
> +            if one_time_price and one_time_price > 0:
При повторном сохранении создастся второй абонемент?
- [ ] Если цена не указана или = 0, то разовый абонемент нужно "выключать".
- [ ] При редактировании должен редактироваться и разовый абонимент (в т.ч. включаться ранее выключенный, если это не сложно).
- [ ] При открытии формы нужно считывать стоимость разового посещения.

2019-03-10 19:18 UTC, INovozhilov requested changes

2019-03-10 19:18 UTC, INovozhilov commented on crm/rules.py
> +def is_one_time_sub(user, obj: SubscriptionsType):
Переименовать надо. А то возвращает инвертированное значение

2019-03-11 10:14 UTC, ciklop requested changes

2019-03-11 10:14 UTC, ciklop commented on crm/views/manager/subscription.py
> +class Update(PermissionRequiredMixin, UserManagerMixin, RevisionMixin, UpdateView):
UserManagerMixin тоже покрывается permissions-ами, нужно тоже убрать

2019-03-12 15:50 UTC, ciklop submitted a review, later dismissed

2019-03-12 17:15 UTC, INovozhilov submitted a review, later dismissed

2019-03-13 17:42 UTC, ciklop approved these changes

2019-03-13 17:42 UTC, merged