Поправил регулярку чтобы учитывалось нижнее подчеркивание
Pomidor-Studio/SportCRM pull request #39
Opened 2019-03-03 21:24 UTC by RomanBoyars

2019-03-04 04:57 UTC, ciklop requested changes

2019-03-04 04:57 UTC, ciklop commented on crm/templates/crm/manager/client/form.html
> +            var idRe = new RegExp("vk.com\/(?<user_id>([A-Za-z0-9]|_)+)");
Зачем "или" 
```
vk.com\/(?<user_id>([A-Za-z0-9_])+)
```

2019-03-05 16:51 UTC, INovozhilov approved these changes

2019-03-05 16:51 UTC, ciklop approved these changes

2019-03-05 16:51 UTC, merged