Функции работы с абонементом одного клинета
Pomidor-Studio/SportCRM pull request #43
Opened 2019-03-05 06:01 UTC by ciklop

Сделать работу с активностью абонемента элементом queryset не получится по одной причине - вычисление занятий абонемента не вычисляется в рамках запроса к бд. По этому все функции завязанные на тренировки - автоматически сами становятся вычисляемыми.

2019-03-07 17:06 UTC, INovozhilov requested changes

2019-03-07 17:06 UTC, INovozhilov commented on crm/models.py
> +                .events_to_date(to_date=self.end_date)[:self.visits_left]
Думаю, что питон не делает такую оптимизацию из коробки, поэтому предлагаю обработать расспространенный случай, когда self.visits_left = 0 и не вызывать ничего - возвращать пустой массив

2019-03-07 17:06 UTC, INovozhilov commented on crm/models.py
> +    def is_active_to_date(self, to_date: date) -> bool:
is_active_at_date и is_active_to_date очень похожие названия с серьезными различиями в функциональности.
Помимо того что их легко перепутать, так ещё и увидеть глазами ошибку будет практически невозможно.
Нужно более различаемые названия придумать.

2019-03-07 17:06 UTC, INovozhilov commented on crm/models.py
> +            _, created = Attendance.objects.get_or_create(
_ - это стандартный алиас для мультиязычности. Замучаемся же, если потребуется использовать.
Может есть более безобидный способ?

2019-03-07 17:33 UTC, ciklop commented on crm/models.py
> +            _, created = Attendance.objects.get_or_create(
https://hackernoon.com/understanding-the-underscore-of-python-309d1a029edc
Это стандартная практика игнорирования значения

2019-03-07 17:34 UTC, ciklop commented on crm/models.py
> +            _, created = Attendance.objects.get_or_create(
Ну либо можно заменить на двойное подчеркивание для отбрасывания значения

2019-03-07 17:43 UTC, ciklop commented on crm/models.py
> +                .events_to_date(to_date=self.end_date)[:self.visits_left]
Ты плохого мнения о питоне.

```c

2019-03-07 17:47 UTC, ciklop commented on crm/models.py
> +    def is_active_to_date(self, to_date: date) -> bool:
Вот тут трудно сказать. а
"Активен на дату", и "активен до даты" - у меня нет подходящих вариантов.
Ну разве что `will_be_active_at_date`

2019-03-07 19:13 UTC, INovozhilov requested changes

2019-03-07 19:13 UTC, INovozhilov commented on crm/models.py
> +    def is_active_to_date(self, to_date: date) -> bool:
Проблема то в том, что один метод не учитывает количество посещений, а другой - учитывает.
Предлоги до/по - это очевидным способом передать не могут (как и will). 
Предлагаю банально дописать without_visits_check.

2019-03-07 19:14 UTC, INovozhilov submitted a review, later dismissed

2019-03-09 04:47 UTC, INovozhilov approved these changes

2019-03-09 04:47 UTC, merged