Изменений баланса ученика
Pomidor-Studio/SportCRM pull request #47
Opened 2019-03-06 16:32 UTC by Vlasov1994

Добавил в модели класс ClientBalance, добавил в класс Client метод позволяющий определить его текущий баланс, добавил отображение истории баланса клиента на страницу с детальной информацией о клиенте.

2019-03-06 16:50 UTC, ciklop requested changes

2019-03-06 16:50 UTC, ciklop commented on crm/models.py
> +        payments = list(ClientBalance.objects.filter(client_id=self.id))
```python
return sum(
    ClientBalance.objects.filter(client_id=self.id).values_list('balance', flat=True), 
    0
)
```

2019-03-06 16:50 UTC, ciklop commented on crm/models.py
> +        payments = list(ClientBalance.objects.filter(client_id=self.id))
Вот и вся функция. И никаких if

2019-03-06 16:50 UTC, ciklop commented on crm/models.py
> +class ClientBalance(models.Model):
```
class ClientBalance(CompanyObjectModel):
```

У нас модели все должны от этой наследоваться + перегенерацию миграции сделай

2019-03-06 16:50 UTC, ciklop commented on crm/models.py
> +    balance = models.FloatField("Баланс", default=0)
Для денег лучше использовать DecimalField

```
>>>1.2-1.0
0.19999999999999996
```

Decimal такой проблемы лишен. Оперирование идёт именно десятичными числами, и проблем округления нет.

2019-03-06 16:50 UTC, ciklop commented on crm/templates/crm/manager/client/detail.html
> +            {% if object.get_client_balance %}
Баланс уже будет всегда у клиента, зачем скрывать если он ноль?

2019-03-06 16:53 UTC, ciklop requested changes

2019-03-06 16:53 UTC, ciklop commented on crm/models.py
> -    balance = models.FloatField("Баланс", default=0)
Пр хорошему это надо оставить - как текущее значение баланса. Чтоб не вычислять по истории сколько у клиента сейчас.

2019-03-06 16:53 UTC, ciklop commented on crm/models.py
> +        payments = list(ClientBalance.objects.filter(client_id=self.id))
Даже так

```python
return sum(self.client_blance_set.values_list('balance', flat=True), 0)
```

2019-03-06 16:53 UTC, ciklop commented on crm/models.py
> -    balance = models.FloatField("Баланс", default=0)
А ClientBalance - это лог изменения баланса. Т.е. текущее значение берем из клиента, а в лог пишем +100 рублей, -100 рублей изменения баланса.

2019-03-06 17:11 UTC, Vlasov1994 commented on crm/templates/crm/manager/client/detail.html
> +            {% if object.get_client_balance %}
@INovozhilov Действительно так нужно сделать? Я просто помню ты мне как-то говорил скрывать баланс если он нулевой? Только по этому сейчас добавил старое ограничение.

2019-03-07 19:16 UTC, INovozhilov commented on crm/templates/crm/manager/client/detail.html
> +            {% if object.get_client_balance %}
Скрывать, если ноль, надо. Будут компании у которых в 99% случаев баланс учеников - ноль.

2019-03-07 19:16 UTC, INovozhilov commented on crm/models.py
> -    balance = models.FloatField("Баланс", default=0)
100% вычислять по истори - дурная затея. Только БД мучать.

2019-03-11 10:30 UTC, ciklop requested changes

2019-03-11 10:30 UTC, ciklop commented on crm/forms.py
> +            'entry_date': DatePickerInput(format='%d.%m.%Y 18:00',
А зачем фиксированные часы?

2019-03-11 10:30 UTC, ciklop commented on crm/models.py
> +        ClientBalance.objects.get_or_create(balance=top_up_amount,
Транзакция нужна

2019-03-11 10:30 UTC, ciklop commented on crm/models.py
> +        ClientBalance.objects.get_or_create(balance=top_up_amount,
Ну и для красоты можно перенести после скобки на новую строку, и тогда indent будет не таким адовым

```python
ClientBalance.objects.get_or_create(
    balance=top_up_amount,
    client=self,
    ...
)
```

2019-03-11 10:30 UTC, ciklop commented on crm/models.py
> +    balance = models.FloatField("Баланс",
Decimal

2019-03-11 10:30 UTC, ciklop commented on crm/views/manager/balance.py
> +        Client.objects.get(id=client_id).update_balance(form.instance.balance)
29-30 строки в транзакцию

2019-03-11 10:30 UTC, ciklop commented on crm/views/manager/client.py
> +        client.add_balance_in_history(-abon_price, default_reason)
70-76  в транзакцию

2019-03-11 17:42 UTC, INovozhilov requested changes

2019-03-11 17:42 UTC, INovozhilov commented on crm/forms.py
> +            'entry_date': DatePickerInput(format='%d.%m.%Y 18:00',
По идее должно по-умолчанию стоять текущее время.

2019-03-11 17:42 UTC, INovozhilov commented on crm/models.py
> +class ClientBalance(CompanyObjectModel):
ClientBalance**ChangeHistory**

2019-03-11 17:42 UTC, INovozhilov commented on crm/models.py
> +    balance = models.FloatField("Баланс",
balance_change_Value или просто change_value

2019-03-11 17:42 UTC, INovozhilov commented on crm/models.py
> +    reason = models.TextField("Причина изменения баланса", null=True, blank=True)
null для строковых полей делать не надо.

2019-03-12 10:17 UTC, ciklop submitted a review, later dismissed

2019-03-12 17:22 UTC, INovozhilov submitted a review, later dismissed

2019-03-12 17:22 UTC, INovozhilov commented on crm/models.py
> +        "Баланс",
Ну название поля можно было бы тоже поменять.

2019-03-12 17:26 UTC, INovozhilov approved these changes

2019-03-12 17:27 UTC, merged