Feature/events
Pomidor-Studio/SportCRM pull request #50
Opened 2019-03-09 07:54 UTC by keldkemp

Закрытие тренировки

2019-03-09 09:05 UTC, INovozhilov commented on crm/models.py
> +    def is_event_closed(self):
Зачем это свойство. Оно лишнее кмк, предлагаю удалить. Достаточно того, что есть is_closed.

2019-03-09 09:15 UTC, INovozhilov requested changes

2019-03-09 09:15 UTC, INovozhilov commented on crm/models.py
> +            raise ValueError("Event is active")
Закрыть тренировку можно и нужно на самой тренировке. Данная проверка это запретит делать. Нужна другая проверка

2019-03-09 09:15 UTC, INovozhilov commented on crm/models.py
> +    def event_is_closed(self):
event_is_closed - не правильное название для метода.
is_closed - это вопрос - закрыта ли тренеровка (ответ да/нет). А твой метод выполняет действия. 
Название должно быть close или close_event

2019-03-09 09:15 UTC, INovozhilov commented on crm/urls.py
> +        'is_closed/',
is_closed - это вопрос, а не действие

2019-03-09 09:15 UTC, INovozhilov commented on crm/views/manager/event_class.py
> +class IsClosed(
нужно использовать RedirectWithActionView вместо RedirectView

2019-03-09 09:15 UTC, INovozhilov commented on crm/views/manager/event_class.py
> +    LoginRequiredMixin,
Нужно использовать PermissionRequiredMixin вместо LoginRequiredMixin с проверкой 
    permission_required = 'event.mark_attendance'

2019-03-09 09:15 UTC, INovozhilov commented on crm/views/manager/event_class.py
> +        event_date = date(self.kwargs['year'],
вместо получения даты и Event.objects.get Нужно использовать EventByDateMixin - он добавляет метод self.get_object()

2019-03-09 10:03 UTC, keldkemp commented on crm/models.py
> +    def is_event_close(self):
Не знаю, как эту проверку назвать

2019-03-09 12:26 UTC, INovozhilov requested changes

2019-03-09 12:26 UTC, INovozhilov commented on crm/templates/crm/manager/event/detail.html
> +  {% if event.is_event_close %}
```
{% if event.is_event_close %}
  {% if not event.is_closed %}
```

Это нечитаемо. Вообще не понятно что ты пытаешься написать и зачем тебе несколько свойств у тренировки. 
Напиши комментариями в коде по-русски что делает тот или иной метод

2019-03-09 12:26 UTC, INovozhilov commented on crm/views/manager/event_class.py
> +    def get(self, request, *args, **kwargs):
Нужно переопределять не get, a do_action от RedirectWithActionView

2019-03-09 14:29 UTC, ciklop commented on crm/models.py
> +    def is_event_close(self):
is_overpast

2019-03-09 14:41 UTC, ciklop requested changes

2019-03-09 14:41 UTC, ciklop commented on crm/models.py
> +        with transaction.atomic():
Тут транзакция не нужна, так как меняем состояние только одного объекта.

2019-03-09 14:41 UTC, ciklop commented on crm/models.py
> +            raise ValueError("Event has not started")
"Event has not started" не очень ясно будет, лучше написать "Event for future date, can't be closed"

2019-03-09 14:41 UTC, ciklop commented on crm/models.py
> +            raise ValueError("Event is closed")
"Event is **already** closed"

2019-03-09 14:41 UTC, ciklop commented on crm/templates/crm/manager/event/detail.html
> +  {% if event.is_event_close %}
После переименования `is_event_close` в `is_overpast` будет понятнее

2019-03-09 14:41 UTC, ciklop commented on crm/views/manager/event_class.py
> +    EventByDateMixin
Миксин всегда должен стоять раньше чем базовый класс, иначе до него может и не дойти обработчик.
У питона - left to rigth method resolving (не совсем так, но в общем смысле да) https://docs.python.org/3/tutorial/classes.html#multiple-inheritance

и view должен называться не IsClosed - это ответ на вопрос состояния, а надо ответить на вопрос что делает эта вьюха `ActionClose`, `ClosingView`, `CloseAction`, `DoClose` 
т.е. 
```python
class BETTER_NAME_THAN_CURRENT(PermissionRequiredMixin, EventByDateMixin, RedirectWithActionView):
    ...
```

2019-03-09 14:41 UTC, ciklop commented on crm/views/manager/event_class.py
> +        return reverse('crm:manager:event-class:event:event-by-date', kwargs=self.kwargs)
Это лучше не переопределять, а задать через pattern_name = 'rever-url-resolve'
Так как родительский get_success_url делает тоже самое, только чуть хитрее

2019-03-09 16:55 UTC, ciklop requested changes

2019-03-09 16:55 UTC, ciklop commented on crm/models.py
> +            raise ValueError("Event is open")
Event is **already** open

2019-03-10 09:09 UTC, keldkemp commented on crm/templates/crm/manager/event/detail.html
> +  }
Я так и не понял, как сделать то, что предложил Кирилл

2019-03-10 17:19 UTC, ciklop approved these changes

2019-03-10 19:06 UTC, INovozhilov approved these changes

2019-03-10 19:06 UTC, merged