GCP
Pomidor-Studio/SportCRM pull request #52
Opened 2019-03-10 13:20 UTC by INovozhilov

Configs for GCP build

2019-03-10 17:34 UTC, ciklop requested changes

2019-03-10 17:34 UTC, ciklop commented on requirements.txt
> +git+https://github.com/citusdata/django-multitenant@97ebc3a95bfb56d494e34b0b4d4f87452d20af09#egg=django-multitenant==2.0.0
Они на pypi последнюю ветку выкатили https://pypi.org/project/django-multitenant/
Так-что можно больше не парится и сделать
```
django-multitenant==2.0.0
```

2019-03-10 17:34 UTC, ciklop commented on sportcrm/settings/gcp_production.py
> +DEBUG = True
Надеюсь временно?

2019-03-10 17:34 UTC, ciklop commented on requirements-dev.txt
> +gunicorn==19.9.0
А зачем он в деве? Кто-то локально запускает джангу через гуникорн? Так-то он больше для хероку нужен был.

2019-03-10 17:34 UTC, ciklop commented on .gcloudignore
> +venv.bak/
плюс

```
.editorconfig
.python-version
.stylelintrc
conftest.py
Procfile
pytest.ini
runtime.txt
**/tests/
```

2019-03-10 19:12 UTC, INovozhilov commented on requirements.txt
> +git+https://github.com/citusdata/django-multitenant@97ebc3a95bfb56d494e34b0b4d4f87452d20af09#egg=django-multitenant==2.0.0
Так у них всё равно всё сыро(

2019-03-10 19:12 UTC, INovozhilov commented on sportcrm/settings/gcp_production.py
> +DEBUG = True
Да, конечно. Надо будет ещё разделять тест от прода в GCP. До этого ещё не дошел.

2019-03-10 19:13 UTC, INovozhilov commented on requirements-dev.txt
> +gunicorn==19.9.0
хз, уберу.

2019-03-11 10:15 UTC, ciklop commented on requirements.txt
> +git+https://github.com/citusdata/django-multitenant@97ebc3a95bfb56d494e34b0b4d4f87452d20af09#egg=django-multitenant==2.0.0
Ну мы же делали такой фокус - потому что у них в pypi не было postgres backend и что-то там поломаное было.  А теперь у них пайпи актуальный, пусть даже и какой есть по "сырости"

2019-03-11 10:21 UTC, ciklop requested changes

2019-03-11 10:21 UTC, ciklop commented on google_tasks/tests.py
> +from django.test import TestCase
Этот файл можно удалять, так как у нас не unittest runner, а pytest runner

2019-03-11 10:21 UTC, ciklop commented on google_tasks/tasks.py
> +    method_to_call = getattr(bot.tasks, method)
Тут ещё проверку на None сделать надо, если такого атрибута нет

NoneType is not callable

2019-03-11 10:21 UTC, ciklop commented on crm/models.py
> +                from google_tasks.tasks import enqueue
Раз переходим на такое - то надо полностью селерю выпиливать. Убирать из конфига, убирать из декораторов и всё прочее связное убирать.

2019-03-11 15:56 UTC, INovozhilov commented on google_tasks/tasks.py
> +    method_to_call = getattr(bot.tasks, method)
А зачем такое отправлять? Но ок. Согласен.

2019-03-11 18:02 UTC, ciklop approved these changes

2019-03-12 17:57 UTC, merged