Feature/vk-bot-signals
Pomidor-Studio/SportCRM pull request #63
Opened 2019-03-13 16:42 UTC by keldkemp

Переделываю сигналы под Гугл Таскс

2019-03-13 16:42 UTC, keldkemp commented
Посмотрите, пожалуйста, правильно делаю?

2019-03-13 16:45 UTC, keldkemp commented on crm/views/manager/client.py
Вот тут я не совсем уверен, как надо сделать

2019-03-13 17:55 UTC, ciklop requested changes

2019-03-13 17:55 UTC, ciklop commented on bot/api/messages/clients_info.py
> +def client_subscriptions_buy(client_subscription):
Вот эти три функции совсем не так должны быть написаны. Посмотри как сделан базовый класс Message, и как сделан CanceledEvent.

Ты во всех трех функциях повторяешь одинаковый код. DRY надо соблюдать. Эти три функции должны быть классом, которые наследуются от Message, и надо переопределять метод `prepare_generalized_msg`

2019-03-13 17:55 UTC, ciklop commented on bot/api/messages/clients_info.py
> +    end_date = '{:%d-%m-%Y}'.format(client_subscription.end_date)
для питона 3.7 можно так `f'{date:%d.%m.%Y}'`
И да, для России характерно использование точки. Мы конечно l10n не используем, но надо блюсти "традиции"

2019-03-13 17:55 UTC, ciklop commented on bot/api/messages/clients_info.py
> +    message.extend([client.name, '!\nВаш баланс состовляет: ', str(balance)])
Грамматическая ошибка

2019-03-13 17:56 UTC, ciklop commented on crm/views/manager/client.py
Ну да, примерно так. Только не code, а response. super().form_valid() возвращает HttpRespose....

2019-03-14 16:06 UTC, ciklop requested changes

2019-03-14 16:06 UTC, ciklop commented on bot/api/messages/clients_info.py
> +class ClientSubscriptionBuy(Message):
Уже лучше, но ещё есть что править.
Во первых - у тебя три класса делают одно и тоже - одинаковый init. Это значит что можно выделить общий `class SubscriptionMessage(Message):` который задаст общий __init__, а уже `class ClientSubscriptionBy(SubscriptionMessage)` будет. И опять становится меньше дублирования кода.

А во-вторых такой момент - обрати внимание на personalized параметр и как он обрабатывается в message.
prepare_genaralized_msg делает только общее сообщение, без имени. Оно потом само дописывается если флаг выставлен.

Это надо, чтоб не думать о логики персонифицирования сообщения в каждом классе. Класс реализует только формирование сообщения конкретного, а персофикация одинаковая для всех. 
Ну покамест. Потом что-то может и изменится

2019-03-14 16:06 UTC, ciklop commented on bot/api/messages/clients_info.py
> +    def __init__(self, client, personalized=False, *, thisclient: Client):
Зачем сюда передавать thisclient если они будут равны? Я конечно догадываюсь что из-за того что self.client: List[Client], но Message это не закон, его тоже можно менять как потребуется.
Можно выделить SingleClientMessage и GroupClientMessage и там немного логику поменять. 
Но в данном случае нужно не тащить ещё раз того-же самого клиента. Пока можно просто сделать this.client[0].balance

2019-03-14 16:06 UTC, ciklop commented on bot/tasks.py
> +    ClientSubscriptionBuy(client_sub.client, clientsub=client_sub).send_message()
Пропустил момент - зачем передавать сюда клиента, а потом надеятся вытащить последнюю подписку?
Это запросто может вызвать такой баг, так как обработка-то асинхронная. Клиенту завели две подписки, и две задачи упали, но ещё не обработались. Когда они попадут в обработку - то оба сообщения будет про одну и тот же абонемент. А первый проданный - никогда не появится в вк.
Передавать надо именно ClientSubscription.id

2019-03-15 07:22 UTC, ciklop approved these changes

2019-03-15 09:17 UTC, merged