Register attendance
Pomidor-Studio/SportCRM pull request #68
Opened 2019-03-15 17:11 UTC by RomanBoyars

2019-03-15 17:57 UTC, ciklop requested changes
Очень грязный PR. Плохо решены конфликты с мастером.

2019-03-15 17:57 UTC, ciklop commented on crm/models.py
> +        attendance = Attendance.objects.get(client=self, event=event)
Проверка на Attendance.DoesNotExist

2019-03-15 17:57 UTC, ciklop commented on crm/models.py
> +        if (attendance.subscription):
Скобки не нужны

2019-03-15 17:57 UTC, ciklop commented on crm/models.py
> +            attendance.subscription.mark_visit()
Нужна транзакция

2019-03-15 17:57 UTC, ciklop commented on crm/models.py
> +        if (attendance.subscription):
Также - скобки и транзакиця

2019-03-15 17:57 UTC, ciklop commented on crm/models.py
> +            attendance.subscription.restore_visit()
Тесты были? ClientSubscription.restore_visit делает attendance.delete. Как потом сработает attendance.restore_visit - не совсем понятно. Скорее всего упадёт, так как save на deleted это плохая идея

2019-03-15 17:57 UTC, ciklop commented on crm/models.py
> +            self.subscription.restore_vusit()
Точно тестов не было, так как тут опечатка. Случай с restore_visit на self.subscription is not None надо проверить.

2019-03-15 17:57 UTC, ciklop commented on crm/templates/crm/manager/event/detail.html
> -<script type="text/javascript">
Почему удалено всё что связанно с закрытием тренировки? Надо аккуратнее решать конфликты. Нужно вернуть всё что лишнее удалено

2019-03-15 17:57 UTC, ciklop commented on crm/views/manager/event_class.py
> +    LoginRequiredMixin,
Никаких LoginRequiredMixin и UserManagerMixin - только PermissionRequiredMixin

2019-03-15 17:57 UTC, ciklop commented on crm/views/manager/event_class.py
> +        event_date = date(self.kwargs['year'],
EventByDateMixin + self.get_object() вместо дублирования кода. DRY!

2019-03-15 17:57 UTC, ciklop commented on crm/views/manager/event_class.py
> +    LoginRequiredMixin,
Тоже что и выше

2019-03-15 17:57 UTC, ciklop commented on crm/views/manager/event_class.py
> +        event_date = date(self.kwargs['year'],
Тоже что и выше

2019-03-15 17:57 UTC, ciklop commented on sportcrm/settings/base.py
> -    'phonenumber_field',
Зачем тут было что-то убирать. Это важные части. Нужно всё вернуть

2019-03-16 13:11 UTC, RomanBoyars commented on crm/models.py
> +        attendance = Attendance.objects.get(client=self, event=event)
get_object_or_404 здесь подойдет?

2019-03-16 13:13 UTC, RomanBoyars commented on crm/models.py
> +            attendance.subscription.restore_visit()
это поправил

2019-03-16 13:13 UTC, RomanBoyars commented on crm/models.py
> +        if (attendance.subscription):
with transaction.atomic?

2019-03-20 18:05 UTC, ciklop approved these changes

2019-03-20 18:05 UTC, merged