Feature/vk_bot_commands
Pomidor-Studio/SportCRM pull request #81
Opened 2019-03-19 14:25 UTC by keldkemp

Добавил уведомлении при Закрытии/Открытии тренировки
Добавил флаг на update_balance при покупки абонемента, поправил стандартное сообщение
Поправил базовый класс
Перенес команды на GoogleTasks

2019-03-19 14:51 UTC, ciklop submitted a review, later dismissed

2019-03-19 15:57 UTC, INovozhilov requested changes

2019-03-19 15:57 UTC, INovozhilov commented on bot/views.py
> -            set_current_tenant(company)
set_current_tenant нужно оставить. Либо доработать enqueue чтобы туда передавался company_id (это предпочтительнее). Тогда можно будет не company вычитывать, а только company_id, что быстрее
И странно, если ты удаляешь использование company, почему её получение осталось.

2019-03-19 15:57 UTC, INovozhilov commented on bot/views.py
> -            set_current_tenant(company)
Можно сделать отдельную очередь с сообщениями от пользователей VK. При их приеме вообще ничего не считывать из БД - только ставить в очередь. И отдельный обработчик таких сообщений

2019-03-19 15:57 UTC, INovozhilov commented on bot/views.py
> +            enqueue('create_answer', data['object'], token)
метода create_answer нет в bot.tasks

2019-03-20 21:14 UTC, ciklop submitted a review, later dismissed

2019-03-22 17:05 UTC, ciklop approved these changes

2019-03-23 12:11 UTC, INovozhilov approved these changes

2019-03-23 12:11 UTC, merged