Locations
Pomidor-Studio/SportCRM pull request #83
Opened 2019-03-19 16:03 UTC by RomanBoyars

2019-03-20 15:33 UTC, INovozhilov requested changes

2019-03-20 15:33 UTC, INovozhilov commented on crm/models.py
> +            Q(date_from__gt=today) |
from зачем проверять?

2019-03-20 15:33 UTC, INovozhilov commented on crm/rules.py
> -rules.add_perm('event_class', rules.is_authenticated & (is_manager | is_coach))
а права на event_class почему убраны? Так задумано?

2019-03-20 15:33 UTC, INovozhilov commented on crm/views/manager/location.py
> +            self.object.delete()
Зачем строку self.object.delete() повторять два раза?

2019-03-20 15:33 UTC, INovozhilov commented on crm/views/manager/location.py
> +    def delete(self, request, *args, **kwargs):
Я так понимаю, что это переопределение, а не проще было вызвать super после того как проверится и сформируется сообщение о наличии тренировок?

2019-03-20 17:34 UTC, RomanBoyars commented on crm/rules.py
> -rules.add_perm('event_class', rules.is_authenticated & (is_manager | is_coach))
видимо при мердже ошибся

2019-03-22 18:56 UTC, ciklop approved these changes

2019-03-23 12:06 UTC, INovozhilov approved these changes

2019-03-23 12:06 UTC, merged